### ISSUE TITLE
PreferencesModule sample

### ISSUE THREAD

**Issue by pritam2102** [WaheedNazir/Kotlin-MVVM-Architecture#4]
Hello.

I have read your mvvm architecure i.e. very good. can you please provide how to use sharedPreference in your sample 

```
@Module
class PreferencesModule {
   /**
     * Provides Preferences object with MODE_PRIVATE
     */
    @Provides
    @Singleton
    fun provideSharedPreference(app: Application):
            SharedPreferences = app.getSharedPreferences("SharedPreferences", Context.MODE_PRIVATE)

}
```

**Comment by pritam2102** [comment]
after R and D sample code found and implemented

**Comment by Rohitsachdeva** [comment]
please share an example of using this in activity or fragment

**Comment by WaheedNazir** [comment]
You can inject like this in activity / fragment 

    @Inject
    lateinit var sharedPreferences: SharedPreferences
    
 To save 
    sharedPreferences.edit().putString("YOUR_KEY","123456").apply()
    
  To retrieve
    sharedPreferences.getString("YOUR_KEY","defaultValue")
